// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTTDP61f0bhFPA-z3xfGzXHW1sscii0k',
    appId: '1:565101432040:web:85e9db75eaaeeafe868d5d',
    messagingSenderId: '565101432040',
    projectId: 'bricol-cf642',
    authDomain: 'bricol-cf642.firebaseapp.com',
    storageBucket: 'bricol-cf642.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClHqJgWzKCa9fGWPBvz6bLHl-iMOrU-M8',
    appId: '1:565101432040:android:3c4bd67e9f3410a4868d5d',
    messagingSenderId: '565101432040',
    projectId: 'bricol-cf642',
    storageBucket: 'bricol-cf642.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqVoLWzjWTiJ_-Mr_1-WqacRpf8eO_10',
    appId: '1:565101432040:ios:74e006c012f463e0868d5d',
    messagingSenderId: '565101432040',
    projectId: 'bricol-cf642',
    storageBucket: 'bricol-cf642.appspot.com',
    iosBundleId: 'com.example.bricol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABqVoLWzjWTiJ_-Mr_1-WqacRpf8eO_10',
    appId: '1:565101432040:ios:74e006c012f463e0868d5d',
    messagingSenderId: '565101432040',
    projectId: 'bricol-cf642',
    storageBucket: 'bricol-cf642.appspot.com',
    iosBundleId: 'com.example.bricol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsTTDP61f0bhFPA-z3xfGzXHW1sscii0k',
    appId: '1:565101432040:web:5dff93daf9e3c7aa868d5d',
    messagingSenderId: '565101432040',
    projectId: 'bricol-cf642',
    authDomain: 'bricol-cf642.firebaseapp.com',
    storageBucket: 'bricol-cf642.appspot.com',
  );

}